"""add_image_dedupe_fields

Revision ID: ddfdadfdbb2f
Revises: 9e504cd87f13
Create Date: 2026-01-08 17:20:59.242834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddfdadfdbb2f'
down_revision: Union[str, Sequence[str], None] = '9e504cd87f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('image_key', sa.String(length=255), nullable=True))
    op.add_column('receipts', sa.Column('image_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_receipts_image_fingerprint'), 'receipts', ['image_fingerprint'], unique=False)
    op.create_unique_constraint('uq_user_receipt_hash', 'receipts', ['user_id', 'image_fingerprint'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_receipt_hash', 'receipts', type_='unique')
    op.drop_index(op.f('ix_receipts_image_fingerprint'), table_name='receipts')
    op.drop_column('receipts', 'image_fingerprint')
    op.drop_column('receipts', 'image_key')
    # ### end Alembic commands ###
